language: node_js
node_js:
  - '10'
  - '8'
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false    
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
