dist: trusty
sudo: false
language: node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - npm install
after_success:
  - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
